package com.caiwei.sunny.mdm.permis.mapper;

import com.caiwei.sunny.mdm.permis.api.domain.PermisResourceDO;
import org.springframework.stereotype.Repository;

@Repository
public interface PermisResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    int deleteByPrimaryKey(Integer tresId);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    int insert(PermisResourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    int insertSelective(PermisResourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    PermisResourceDO selectByPrimaryKey(Integer tresId);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    int updateByPrimaryKeySelective(PermisResourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    int updateByPrimaryKey(PermisResourceDO record);
}