package com.caiwei.sunny.mdm.permis.mapper;

import com.caiwei.sunny.mdm.permis.api.domain.TermsCodeDO;
import org.springframework.stereotype.Repository;

@Repository
public interface TermsCodeMapper {

    TermsCodeDO findByTermsCode(String termsCode);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    int deleteByPrimaryKey(Integer ttcId);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    int insert(TermsCodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    TermsCodeDO selectByPrimaryKey(Integer ttcId);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    int updateByPrimaryKey(TermsCodeDO record);
}