package com.caiwei.sunny.mdm.dict.mapper;

import com.caiwei.sunny.mdm.dict.api.domain.TermsValueDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TermsValueMapper {

    List<TermsValueDO> findByTermsCode(String termsCode);

    TermsValueDO findByTermsCodeAndValueCode(@Param("termsCode") String termsCode, @Param("valueCode") String valueCode);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    int deleteByPrimaryKey(Integer ttvId);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    int insert(TermsValueDO record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    TermsValueDO selectByPrimaryKey(Integer ttvId);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @author Administrator
     * @date 2017-11-06 14:52:56
     */
    int updateByPrimaryKey(TermsValueDO record);
}